<a href="https://colab.research.google.com/github/gourim2523-arch/numpy_assignment/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/titanic_dataset.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [ ]:
import numpy as np
arr = np.arange(10, 50)
print(arr)
matrix = arr.reshape(4, 10)
print(matrix)
last_column = matrix[:, -1]
print(last_column)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[19 29 39 49]


In [ ]:
import numpy as np
a=np.full((3,3),5)
b=np.arange(1,10).reshape(3,3)
print("matrix a:")
print(a)
print("matrix b:")
print(b)
addition=a+b
print("addition(a+b):")
print(addition)
multiplication=a*b
print("multiplication(a*b):")
print(multiplication)
transpose_result = multiplication.T
print("Transpose of Multiplication Result:")
print(transpose_result)

matrix a:
[[5 5 5]
 [5 5 5]
 [5 5 5]]
matrix b:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
addition(a+b):
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
multiplication(a*b):
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose of Multiplication Result:
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [ ]:

import numpy as np
arr = np.random.randint(10, 101, 15)

print("Original Array:")
print(arr)
count = np.sum(arr > 50)
arr[arr > 50] = -1

print("Modified Array:")
print(arr)

print("Number of values replaced:", count)

Original Array:
[79 17 75 76 47 84 11 98 24 46 98 23 74 96 81]
Modified Array:
[-1 17 -1 -1 47 -1 11 -1 24 46 -1 23 -1 -1 -1]
Number of values replaced: 9


In [ ]:
arr=np.random.rand(5,4)
print(arr)

[[0.48372316 0.43788882 0.53210799 0.23893257]
 [0.49998385 0.59293799 0.86424974 0.26111777]
 [0.17212901 0.02784026 0.0561838  0.7800945 ]
 [0.9649634  0.97782188 0.90294957 0.05342126]
 [0.94736049 0.08908549 0.40190247 0.89367874]]


In [ ]:
row_sum=arr.sum(axis=1)
print(row_sum)

[1.69265254 2.21828935 1.03624757 2.89915611 2.33202719]


In [ ]:
max_row=np.argmax(row_sum)
print(max_row)

3


In [ ]:
print(arr[max_row])

[0.9649634  0.97782188 0.90294957 0.05342126]


In [ ]:
for i in range(5):
  min_val=arr[i].min()
  max_val=arr[i].max()
  arr[i]=(arr[i]-min_val)/(max_val-min_val)
  print("normalized array:")
  print(arr)

normalized array:
[[0.83496286 0.67862526 1.         0.        ]
 [0.3960428  0.55016188 1.         0.        ]
 [0.19180849 0.         0.03767814 1.        ]
 [0.98608993 1.         0.91900448 0.        ]
 [1.         0.         0.36447173 0.9374539 ]]
normalized array:
[[0.83496286 0.67862526 1.         0.        ]
 [0.3960428  0.55016188 1.         0.        ]
 [0.19180849 0.         0.03767814 1.        ]
 [0.98608993 1.         0.91900448 0.        ]
 [1.         0.         0.36447173 0.9374539 ]]
normalized array:
[[0.83496286 0.67862526 1.         0.        ]
 [0.3960428  0.55016188 1.         0.        ]
 [0.19180849 0.         0.03767814 1.        ]
 [0.98608993 1.         0.91900448 0.        ]
 [1.         0.         0.36447173 0.9374539 ]]
normalized array:
[[0.83496286 0.67862526 1.         0.        ]
 [0.3960428  0.55016188 1.         0.        ]
 [0.19180849 0.         0.03767814 1.        ]
 [0.98608993 1.         0.91900448 0.        ]
 [1.         0.         0.364471

In [ ]:
import numpy as np
arr=np.random.rand(5,4)
print("original array:")
print(arr)
sums=arr.sum(axis=1)
print("row_sum:")
print(sums)
row_max=np.argmax(sums)
print("row_max:")
print(row_max)
print(arr[max_row])
normalized=np.empty_like(arr)
for i in range(5):
  minimum=arr[i].min()
  maximum=arr[i].max()
  normalized[i]=(arr[i]-minimum)/(minimum-maximum)
print("Normalized Array:")
print(normalized)


original array:
[[0.10248289 0.49569584 0.50957012 0.50858817]
 [0.78003875 0.17961703 0.80304261 0.63111585]
 [0.16812782 0.51592967 0.26967473 0.85120051]
 [0.13211198 0.88626264 0.94743091 0.27107713]
 [0.30351368 0.79277526 0.97735444 0.91207467]]
row_sum:
[1.61633703 2.39381424 1.80493273 2.23688265 2.98571806]
row_max:
4
[0.13211198 0.88626264 0.94743091 0.27107713]
Normalized Array:
[[-0.         -0.96591817 -1.         -0.99758787]
 [-0.96310087 -0.         -1.         -0.72422248]
 [-0.         -0.50917254 -0.14866193 -1.        ]
 [-0.         -0.92497627 -1.         -0.17044269]
 [-0.         -0.72607893 -1.         -0.90312285]]


In [ ]:
arr=np.array([1,3,5,7,9,1,5,5])
unique,count=np.unique(arr,return_counts=True)
print("unique_elements:")
print(unique)
duplicates = unique[count > 1]

print("Duplicate Elements:")
print(duplicates)

unique_elements:
[1 3 5 7 9]
Duplicate Elements:
[1 5]


In [ ]:
arr = np.arange(1, 37).reshape(6, 6)
print("Original Array:")
print(arr)
submatrix = arr[1:5, 1:5]
print("Middle 4x4 Submatrix:")
print(submatrix)
even_numbers = submatrix[submatrix % 2 == 0]

print("Even Numbers:")
print(even_numbers)

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Middle 4x4 Submatrix:
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even Numbers:
[ 8 10 14 16 20 22 26 28]


In [ ]:
arr=np.arange(12).reshape(3,4)
print("Original Array:")
print(arr)
arr2=arr.reshape(2,6)
print("reshaped array:")
print(arr2)
arr3=arr2.flatten()
print("flattened array:")
print(arr3)
arr4=arr3.reshape(4,3)
print("Reshaped to (4,3):")
print(arr4)



Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshaped array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
flattened array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to (4,3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print("original array:")
print(a)

a = np.vstack((a, [5, 6]))

print("After Adding Row:")
print(a)

a = np.hstack((a, [[7], [8], [9]]))

print("\nAfter Adding Column:")
print(a)

original array:
[[1 2]
 [3 4]]
After Adding Row:
[[1 2]
 [3 4]
 [5 6]]

After Adding Column:
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
arr=np.concatenate((a,b,c))
print("concatenated array:")
print(arr)
matrix=arr.reshape(3,3)
print("reshaped matrix:")
print(matrix)
diagonal=np.diag(matrix)
print("diagonal matrix:")
print(diagonal)



concatenated array:
[1 2 3 4 5 6 7 8 9]
reshaped matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal matrix:
[1 5 9]


In [ ]:
arr=np.arange(1,21)
print("original array:")
print(arr)
result=arr[(arr % 3==0)|(arr % 5==0)]
print("Values divisible by 3 or 5:")
print(result)
count=len(result)
print("Count:")
print(count)

original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Values divisible by 3 or 5:
[ 3  5  6  9 10 12 15 18 20]
Count:
9


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/titanic_dataset.csv')
data


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/titanic_dataset.csv")

In [ ]:
print(df.head(10))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54

In [ ]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [ ]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [ ]:
print(df.groupby('Sex')['Survived'].mean() * 100)

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64


In [ ]:
print(df['Age'].mean())
print(df['Age'].median())
print(df['Age'].std())

29.69911764705882
28.0
14.526497332334044


In [ ]:
print(df['Pclass'].value_counts())

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [ ]:
print(df[(df['Sex'] == 'female') &
         (df['Age'] < 18) &
         (df['Survived'] == 1)])

     PassengerId  Survived  Pclass  \
9             10         1       2   
10            11         1       3   
22            23         1       3   
39            40         1       3   
43            44         1       2   
58            59         1       2   
68            69         1       3   
84            85         1       2   
156          157         1       3   
172          173         1       3   
184          185         1       3   
208          209         1       3   
233          234         1       3   
237          238         1       2   
307          308         1       1   
329          330         1       1   
381          382         1       3   
389          390         1       2   
435          436         1       1   
446          447         1       2   
448          449         1       3   
469          470         1       3   
479          480         1       3   
504          505         1       1   
530          531         1       2   
535         

In [ ]:
import pandas as pd

df = pd.read_csv("/content/titanic_dataset.csv")

df['Age'] = df['Age'].fillna(df['Age'].median())

print(df['Age'])

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64


In [ ]:
import numpy as np

df['age_group'] = np.where(df['Age'] < 18, 'Child',
                    np.where(df['Age'] <= 60, 'Adult', 'Senior'))

print(df[['Age', 'age_group']].head())

    Age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult


In [ ]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'age_group'],
      dtype='object')


In [ ]:
print(df.nlargest(5, 'Fare'))

     PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   
27            28         0       1      Fortune, Mr. Charles Alexander   
88            89         1       1          Fortune, Miss. Mabel Helen   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  \
258  female  35.0      0      0  PC 17755  512.3292          NaN        C   
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C   
737    male  35.0      0      0  PC 17755  512.3292         B101        C   
27     male  19.0      3      2     19950  263.0000  C23 C25 C27        S   
88   female  23.0      3      2     19950  263.0000  C23 C25 C27        S   

    age_group  
258     Adult  
679     Adult  
737     Adult  
27      Adult  
88      Adul

In [ ]:
print(df.groupby(['Pclass', 'Sex'])['Fare'].mean())

Pclass  Sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64


In [ ]:
df.rename(columns={
    'Sex': 'gender',
    'Fare': 'ticket_fare'
}, inplace=True)

print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket  ticket_fare Cabin Embarked age_group  
0      0         A/5 21171       7.2500   NaN        S     Adult  
1      0          PC 17599      71.2833   C85        C     Adult  
2      0  STON/O2. 3101282       7.9250   NaN        S     Adult  
3      0            113803      53.1000  C123       

In [ ]:
print(df.groupby('Pclass')['Survived'].value_counts())

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64


In [ ]:
print(df.groupby(['Pclass', 'gender'])['Age'].mean())

Pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64
